#!/bin/bash
# WF 2018-01-16
# pretty print the QueenVictoriaWikiData property and item cache example
for purpose in Properties Items
do
  cat QueenVictoriaWikiData${purpose}.xml | xmlstarlet fo > QueenVictoriaWikiData${purpose}Formatted.xml
done
